### PR TITLE
Index the mongoId

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

So that we can support delete: https://github.com/LD4P/sinopia_indexing_pipeline/issues/242

### CODE REVIEW

**Review by justinlittman — CHANGES_REQUESTED** [review]
I think this is indexing the resource ID, not the mongo ID.

Also, probably when to index for templates in addition to resources.

**Comment by jcoyne** [comment]
@justinlittman Can you direct me to where we have a mongo id?

**Comment by justinlittman** [comment]
image

**Comment by jcoyne** [comment]
@justinlittman I've updated to use that.

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
